highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
environment: production
url: "http://garymm.org" # Sitemap base URL.
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-jupyter-notebook
  - jekyll-twitter-plugin
  - jekyll_picture_tag
picture:
  source: assets
jupyter_notebook:
  prompt: false
kramdown:
  math_engine: katex
